framework:
    messenger:
        transports:
            task_deletion:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: task_deletion
                        type: direct
                    queues:
                        task_deletion: ~
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
        routing:
            'App\Message\TaskDeletionMessage': task_deletion