services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DATABASE_URL: "mysql://todoapp:todopass@database:3306/todo?serverVersion=8.0.32&charset=utf8mb4"
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_DATABASE: 'todo'
      MYSQL_USER: 'todoapp'
      MYSQL_PASSWORD: 'todopass'
    ports:
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data: