services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      DATABASE_URL: "mysql://todoapp:todopass@database:3306/todo?serverVersion=8.0.32&charset=utf8mb4"
    volumes:
      - ./src:/var/www/html/src:cached
      - ./config:/var/www/html/config:cached
      - ./public:/var/www/html/public:cached
    depends_on:
      database:
        condition: service_healthy
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  database:
    image: mysql:8.0.32
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]      
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_DATABASE: 'todo'
      MYSQL_USER: 'todoapp'
      MYSQL_PASSWORD: 'todopass'
    ports:
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql
      - ./phpstan.neon.dist:/var/www/html/phpstan.neon.dist
volumes:
  database_data: